/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package daojdbc;

import model.dao.DaoFactory;
import model.dao.SellerDao;
import model.entities.Seller;

/**
 * 
 * @author fabio
 */

public class App {
    
    public static void main(String[] args) {
        
        SellerDao sellerDao = DaoFactory.createSellerDao();
        
        System.out.println("=== Test 1: seller findById ===");
        Seller seller = sellerDao.findById(3);
        
        System.out.println(seller);
    }
}
